### ISSUE TITLE
cannot connect classic controller/nunchuck

### ISSUE THREAD

**Issue by NishantMajumdar** [v1993/linuxmotehook2#3]
how to like connect my classic controller coz like after plugging it in and opening cemu (lutris) it dosent recognize . like it recognizes the buttons on the wiimote itself just fine (dsu) but for any extention like nunchuck or classiccontroller it dosent get recognized. like when i press the buttons to map the input it is not recognized

**Comment by v1993** [comment]
I've replied to you in discord. For anyone who comes across this later on - extensions are connected as a second device.

**Comment by NishantMajumdar** [comment]
it dosent show as a second controller in cemu, it just shows controller 1
