### ISSUE TITLE
No config file specified

### ISSUE THREAD

**Issue by JCionx** [v1993/linuxmotehook2#7]
Hi! Today I just installed linuxmotehook2 on my computer to play on Cemu with a Wiimote. But when I run the program, it tells me this "No config file specified - call with `--help' for usage information." How can I create a config file?

**Comment by v1993** [comment]
You can refer to included `ExampleConfig.ini` for general config structure. I'd suggest to start with an empty file and continue from there.

**Comment by JCionx** [comment]
> You can refer to included `ExampleConfig.ini` for general config structure. I'd suggest to start with an empty file and continue from there.

But where and how to create the file? (Sorry, I'm completely new to linux)
